.Brewfile: '~/.Brewfile'
.aliases: '~/.aliases'
.ansible-galaxy: '~/.ansible_galaxy'
.editorconfig: '~/.editorconfig'
.gitignore-global: '~/.gitignore-global'
.rvmrc: '~/.rvmrc'
.vimrc: '~/.vimrc'
.zshrc: '~/.zshrc'
